### PR TITLE
Fix rapidities in pythia IS modules and make constants consistent

### LINKED ISSUE #158: Use the correct value for fmToGeVinv constant
In `JetScapeConstants.h` there is an inconsistency between `hbarC` and `fmToGeVinv`. While the first one is set to the physical value `static const double hbarC = 0.197327053;` the latter is just set to `5.0`.

From the coding perspective both variables should be `const`:
```
static const double hbarC = 0.197327053;

static const double fmToGeVinv = 1.0 / hbarC;
```

### LINKED ISSUE #159: Use pseudorapidity in the pythia initial state modules
When using pythia in the initial state we should use the rapidity and pseudorapidity consistently. In `JetscapeParticles.cc` we initialize the $p_z$ component of the momenta with the pseudorapidity $\eta$:

https://github.com/JETSCAPE/JETSCAPE/blob/68a45ce4adaf900b3e5eb40f3c111d7b287a8017/src/framework/JetScapeParticles.cc#L45-L55

In `PythiaGun.cc` we initialize the partons with the rapidity instead:

https://github.com/JETSCAPE/JETSCAPE/blob/68a45ce4adaf900b3e5eb40f3c111d7b287a8017/src/initialstate/PythiaGun.cc#L278-L290

Then one would have to use $p_z=m_T \cosh y$ to initialize particles in the framework. 

In `PGun.cc` just for consistency, the value of the pseudorapidity should be used as well, even if it coincides with the rapidity in the cosidered case $y=0$.

### PR DESCRIPTION
**Pull request by Hendrik1704**
This PR closes #158 and closes #159. It introduces a consistent definition of hbarC and its inverse. In the pythia initial state modules, the pseudorapidity is used consistently.

### CODE REVIEW

File: src/initialstate/PGun.cc [hunk 1]
```diff
@@ -16,6 +16,7 @@
 
 #include "PGun.h"
 #include "JetScapeParticles.h"
+#include "JetScapeConstants.h"
```
Comment (jhputschke) [inline src/initialstate/PGun.cc:19]: Is this include needed here?

Comment (Hendrik1704) [reply src/initialstate/PGun.cc:19]: Not really. I will remove it.

**Comment by latessa** [comment]
The test reference data has now been updated to reflect the changes in this PR.
